#!/usr/bin/env bash

buildlinker () {
  which netstat || exit 1
  echo "The program ss was not found."
  echo "Linking /usr/local/bin/ss to $(which netstat)"
  ln -sf $(which netstat) /usr/local/bin/ss
}

which ss || buildlinker

mkdir -p /opt/net-gargoyle/workspace/ 2>/dev/null
cp netMon.py /opt/net-gargoyle/workspace/
cp netSet.py /opt/net-gargoyle/workspace/
cp netCheck.py /opt/net-gargoyle/workspace/
cp netGargoyle.py /opt/net-gargoyle/workspace/
cp net-gargoyle /usr/local/bin/
cp reportIps /usr/local/bin
chmod +x /usr/local/bin/reportIps
cp requirements.txt /opt/net-gargoyle/workspace/
chmod +x /usr/local/bin/net-gargoyle
cd /opt/net-gargoyle/workspace
python3 -m venv ngvenv
source ngvenv/bin/activate
pip3 install -r requirements.txt
