#!/usr/bin/env bash

mkdir -p /opt/net-gargoyle/workspace/ 2>/dev/null
cp netMon.py /opt/net-gargoyle/workspace/
cp netSet.py /opt/net-gargoyle/workspace/
cp netGargoyle.py /opt/net-gargoyle/workspace/
cp net-gargoyle /usr/local/bin/
cp requirements.txt /opt/net-gargoyle/workspace/
chmod +x /usr/local/bin/net-gargoyle
cd /opt/net-gargoyle/workspace
python3 -m venv ngvenv
source ngvenv/bin/activate
pip3 install -r requirements.txt
