#!/usr/bin/env bash
if [ -e /opt/net-gargoyle/workspace/gargoyle.json ]; then
  echo " Existing config found! /opt/net-gargoyle/workspace/gargoyle.json      "
  exit 0
mkdir -p /opt/net-gargoyle/workspace/ 2>/dev/null
echo "{" > /opt/net-gargoyle/workspace/gargoyle.json
echo "  \"MAXSTARTSIZE\": \"500000000\"," >>  /opt/net-gargoyle/workspace/gargoyle.json
echo "  \"MAXRUNSIZE\": \"500000000\"" >>  /opt/net-gargoyle/workspace/gargoyle.json
echo "}" >> /opt/net-gargoyle/workspace/gargoyle.json
cp *.py /opt/net-gargoyle/workspace/
cp net-gargoyle.service /opt/net-gargoyle/workspace/
cp net-gargoyle /usr/local/sbin/
cp reportIps /usr/local/sbin
cp kill-netg /usr/local/sbin/
chmod +x /usr/local/sbin/kill-netg
chmod +x /usr/local/sbin/reportIps
chmod +x /usr/local/sbin/net-gargoyle
cp requirements.txt /opt/net-gargoyle/workspace/
cp run_regression_tests /opt/net-gargoyle/workspace/
cp gargoyle_regression_test.py /opt/net-gargoyle/workspace/
cd /opt/net-gargoyle/workspace
python3 -m venv ngvenv
source ngvenv/bin/activate
pip3 install --upgrade pip
pip3 install -r requirements.txt
ls gargoyle.db || python3 net_set.py
cp net-gargoyle.service /usr/lib/systemd/system/net-gargoyle.service
systemctl enable net-gargoyle && rm -rf net-gargoyle.service install BUILD
