#!/usr/bin/env bash
valx=$(pgrep -f "python3 net_mon.py")
if [ -n "$valx" ]; then
  echo "$valx" | while read line; do
    echo "Found $line to kill.";
    kill -9 "$line";
  done
else
  echo "No processes matched python3 net_mon.py, nothing to kill.";
fi
