#!/bin/sh
mkdir -p /opt/net-gargoyle/workspace/ 2>/dev/null
chmod +x /usr/local/bin/net-gargoyle
chmod +x /usr/local/bin/reportIps
chmod +x /opt/net-gargoyle/workspace/install
/opt/net-gargoyle/workspace/install
exit 0
