#!/bin/sh
mkdir -p /opt/net-gargoyle/workspace/ 2>/dev/null
cp net_mon.py /opt/net-gargoyle/workspace/
cp net_set.py /opt/net-gargoyle/workspace/
cp net_check.py /opt/net-gargoyle/workspace/
cp net_gargoyle.py /opt/net-gargoyle/workspace/
cp net-gargoyle /usr/local/bin/
cp reportIps /usr/local/bin
chmod +x /usr/local/bin/reportIps
cp requirements.txt /opt/net-gargoyle/workspace/
chmod +x /usr/local/bin/net-gargoyle
cd /opt/net-gargoyle/workspace
python3 -m venv ngvenv
source ngvenv/bin/activate
pip3 install -r requirements.txt
ls gargoyle.db || python3 net_set.py
exit 0
