#!/usr/bin/env bash

ipvfour () {
  python3 netCheck.py | grep -oP "[0-9]{3}\.[0-9]+\.[0-9]+\.[0-9]+" | sort -u
 }
 
ipvsix () {
  python3 netCheck.py | grep -oP "(([0-9a-fA-F]{1,4}:){7,7}[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,7}:|([0-9a-fA-F]{1,4}:){1,6}:[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,5}(:[0-9a-fA-F]{1,4}){1,2}|([0-9a-fA-F]{1,4}:){1,4}(:[0-9a-fA-F]{1,4}){1,3}|([0-9a-fA-F]{1,4}:){1,3}(:[0-9a-fA-F]{1,4}){1,4}|([0-9a-fA-F]{1,4}:){1,2}(:[0-9a-fA-F]{1,4}){1,5}|[0-9a-fA-F]{1,4}:((:[0-9a-fA-F]{1,4}){1,6})|:((:[0-9a-fA-F]{1,4}){1,7}|:)|fe80:(:[0-9a-fA-F]{0,4}){0,4}%[0-9a-zA-Z]{1,}|::(ffff(:0{1,4}){0,1}:){0,1}((25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])\.){3,3}(25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])|([0-9a-fA-F]{1,4}:){1,4}:((25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])\.){3,3}(25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9]))" | sort -u
 }

cd /opt/net-gargoyle/workspace/
ls gargoyle.db || exit 1
source ngvenv/bin/activate
echo "+ STARTING IP REPORT $(date +%Y%m%d%H%M%S)"
echo "+ Net Gargoyle Report $(sha256sum gargoyle.db)"
echo "+ executed on $(hostname) as $(whoami)"
echo
echo "+ IPv4 unique IPs found in the gargoyle.db file:"
echo
ipvfour
echo
echo "+ IPv6 unique IPs found in the gargoyle.db file:"
echo
ipvsix
echo
